using MasterService.Application.Interfaces;
using MasterService.Domain.Entities;
using MasterService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace MasterService.Infrastructure.Repositories;

public class PartRepository : IPartRepository
{
    private readonly MasterDbContext _context;

    public PartRepository(MasterDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<PartMaster>> GetAllAsync()
    {
        return await _context.PartMasters
            .Where(p => p.IsDeleted != 1) // Logic to exclude deleted items
            .ToListAsync();
    }

    public async Task<PartMaster?> GetByIdAsync(int id)
    {
        return await _context.PartMasters
            .FirstOrDefaultAsync(p => p.PartId == id);
    }

    public async Task<int> AddAsync(PartMaster part)
    {
        // Set default audit data if not provided
        part.CreatedOn = DateTime.Now;

        await _context.PartMasters.AddAsync(part);
        await _context.SaveChangesAsync();

        return part.PartId; // Return the identity ID generated by SQL
    }
}