version: '3.8'

services:
  # --- MASTER SERVICE API ---
  master-service:
    image: masterservice-api
    container_name: master-api-service
    build:
      context: .
      dockerfile: Apps/MasterService/MasterService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Use the special DNS name for Windows Host
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=FDTest;User Id=FlightDeck_User;Password=FlightDeck_User@2024;TrustServerCertificate=True
    ports:
      - "8080:8080"
