name: Master Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Apps/MasterService/**'
      - 'docker-compose.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Apps/MasterService/MasterService.Api/Dockerfile
          push: true
          # MANUAL LOWERCASE HERE:
          tags: |
            ghcr.io/${{ github.repository_owner }}/systel-master-api:latest
            ghcr.io/${{ github.repository_owner }}/systel-master-api:${{ github.sha }}